#配置数据源
spring:
  datasource:
    readsize: 2
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.198.128:3306/permissionTest?characterEncoding=UTF-8
    username: root
    password: 1234
  read1:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.198.128:3306/e3mall?characterEncoding=UTF-8
    username: root
    password: 1234
  read2:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.198.128:3306/test?characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
    properties:
      hibernate:
        use-new-id-generator-mappings: true
        show_sql: true
        hbm2ddl:
          auto: update

#spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect
#spring.jpa.database=mysql
#spring.jpa.generate-ddl=true
#就是hibernate.hbm2ddl.auto,具体说明可以看README
#spring.jpa.hibernate.ddl-auto=update
#通过方法名解析sql的策略,具体说明可以看README,这里就不配置了
#spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.DefaultComponentSafeNamingStrategy
#spring.jpa.show-sql=true
#spring.jpa.properties.*
#spring.jpa.properties.hibernate.hbm2ddl.auto=update
#spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.use-new-id-generator-mappings=true
